- Snoopy.class.php
- expandFns.php
To prepare for unblocking request on enwiki.
> Replace testwiki with enwiki values/constants/hard-coded data

- Page.php
- Snoopy.class.php
- Template.php
- expandFns.php
updating and hacking Snoopy library, removing code no longer needed in
expandFns.php.
See https://phabricator.wikimedia.org/T128926 for bug report.
> fixing login issue

- Template.php
And also some minor whitespace cleanup.
> Fixing errors introduced in pull request #109

- Template.php
Sometimes people add a page specific URL to a page number
> do not mess with pages that contain http.

- Template.php
Really need to return before adding volume
> fix ZooKeys better

- expandFns.php
It is not doing its job where it is now.
> I believe this needs to go after UTF-8 stuff

- Template.php
Actually using DEV branch this time.  :-)
>  format_title_text to more things

- .travis.yml
- Template.php
- expandFns.php
- tests/phpunit/expandFnsTest.php
Capitalization test cases implemented and passing
> Capitalization & test cases

- Parameter.php
Double negatives confused me.
Logic is opposite of what it should be
> URLS in pages was done wrong

- Template.php
This low quality search should be done last.
> do year finding after access date etc.

- Template.php
add_if_new will see year, etc.
> add_if_new was wrong choice

- Template.php
- tests/phpunit/TemplateTest.php
More test cases and @codeCoverageIgnore blocks in Template.php
> Codecov: Improve code coverage

- Template.php
- tests/phpunit/TemplateTest.php
> convert from journal to book

- Template.php
- constants.php
- tests/phpunit/TemplateTest.php
> Handle bad external data better

- tests/phpunit/TemplateTest.php
Fixes lack of testing of ISBN code
- Add ISBN10 to ISBN13 tests
- This was previously merged into master by accident instead of development
-
> Test ISBN code

- Template.php
Fixed open access code adding URL that will be updated by later bot runs or duplicates PMC etc.
> Open Access might be PMC, etc.

- wikiFunctions.php
More readable with indenting etc.
Fixes nothing
> white space formatting

- Template.php
fixed readability a little bit
> Standardize on elseif vs else if

- expandFns.php
Puts brackets about else/if and switched else if to elseif
> format code for readability

- Template.php
- expandFns.php
- tests/phpunit/TemplateTest.php
> Improve handling of external text, and of text already in a template

- constants.php
> Another journal with an annoying name

- Template.php
Fixes variety in coding style
- else if vs elseif
> prefer elseif over else if, just because

- DOItools.php
Fixes Nothing
- Else if to elseif
- {} around consequences
> More readable

- Template.php
- tests/phpunit/TemplateTest.php
Do not flag placeholders as bad DOIs
> Do not flag placeholders as bad DOIs

- doibot.php
> Format user seen output

- tests/phpunit/TemplateTest.php
Removes comments that are not true
> Those comments are wrong

- Page.php
- Template.php
- category.php
- doibot.php
Moves HTML_OUTPUT stuff into fewer places
> Use html_echo

- doibot.html
Fixes my own overly picky mind
> Fix international Character

- Template.php
- tests/phpunit/TemplateTest.php
Fixes Missing tests
Also fixes using non-existent abs database author list
Also resets SLOW to TRUE
> copy all my tests into GitHub

- Template.php
- tests/phpunit/TemplateTest.php
Fixes the ignoring of DOIs in cite book
> Some books have DOIs

- constants/parameters.php
Fixes missing chapter-format parameter.  
Found another while looking it up.
> add more paramters

- Template.php
Fixes failure to check for errors
> More error checking

- tests/phpunit/TemplateTest.php
Fixes depending upon jstor to do that for us
> de-encode SICI

- Template.php
Fixes replacing existing first1
> Treat first1 same as first2, etc

- DOItools.php
> corporations are not people

- DOItools.php
- Template.php
- gadgetapi.php
- login.php
- wikiFunctions.php
This just more gracefully handles errors.
Also adds @ symbol to explicitly show we ignore error codes that are not a return code
> better error handling in json

- Template.php
- constants.php
Fixes google data
Also, added catch-all for authors that end in "inc" or "inc.".
I hereby apologize in advance to any person whose actual name is "inc"
> Nielsen Business Media, Inc is google "author"

- DOItools.php
- Template.php
- docs/CONTRIBUTING.md
Fixes code formatted old style.  I will fix errors soon.
> Replace CamelCase with underscores

- Template.php
Sometimes jstor URL has SICI information in it
> Extract SICI information before processing JSTOR URL

- Template.php
- constants.php
> Better detecting of publishers listed as authors

- Template.php
- tests/phpunit/TemplateTest.php
Fixes missing jstor support
Includes test case
> add jstor support using Citoid

- Template.php
Fixes random "on jstor" added to titles.
> citoid sometimes adds "on jstor" to titles

- Template.php
- tests/phpunit/TemplateTest.php
Books and journals are incomplete() for different reasons.
Re-based this pull
I have no real example of this being a good idea, but it seems like a good idea.
> incomplete() is different for books

- Template.php
- tests/phpunit/TemplateTest.php
Cite Book wants relevant pages of book.  Not total pages.
> Do not add total pages to books

- Template.php
Fixes running the bot a second time does more work
> If we find an ISBN, then use GOOGLE to expand it

- Template.php
> Wrong function called — empty vs blank

- Page.php
- Template.php
This fixed nothing, but is a good idea
> public vs protected

- Page.php
Working on the other bugs; I noticed this
> Remove unused code

- Template.php
Fixes google dates.   Often come in as YYYY-MM
Change 2012-11 to November 2012
> fix Google dates

- wikiFunctions.php
> Daniel proxy is long gone

- tests/phpunit/TemplateTest.php
Fixes lack of check on last submission
> add google date test case

- tests/phpunit/wikiFunctionsTest.php
- wikiFunctions.php
Document problems in code and return NULL for failures and PHP 7
Adds error checking.
Does not actually get this working, but moves us much closer to working
> Add SQL error checking

- tests/phpunit/wikiFunctionsTest.php
- wikiFunctions.php
URL http to verify user's existence
> Fix is_valid_user and add a test

- Template.php
Fixes not dealing with dx.doi.org being down.
This happened to me one time
> handle dx.doi.org failures

- Page.php
- tests/phpunit/wikiFunctionsTest.php
Not that great since actual writing is blocked, but does check a few things and found a few initialized things in error page.
> Test write() errors

- category.php
That is printed a couple lines above
Maybe the right thing is to remove other printing instead???
> remove duplicate printing

- Template.php
Fixes citations with journal=series and title=chapter
> deal with books vs journals information better

- Page.php
Fixes too many things being public thatnare not actually accessed outside the class.
Ran across this when trying figure out something else.
> Protected vs Public variables 

- Template.php
Fixes code bombing when database is down
> Handle simplexml_load_file errors

- Page.php
Same code exists in two places.
> reduce code duplication

- DOItools.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/wikiFunctionsTest.php
I think this pretty much covers all the code.
Most of the uncovered code is like this:
if ($bad) {
die;  // no code coverage here
}
> more tests and Code Coverage flagging

- Template.php
- credentials/crossref.login
This is a separate project from other key. 
This is good to have them as separate projects within google.
Previous problems was Travis adding new IP addresses that google did not know about.
Fixed now on this key
> Fix  Google Key

- Template.php
Fixes some of the ugliest bot output
Honestly, not sure why we print out this detail at all
> Better output

- Template.php
- tests/phpunit/TemplateTest.php
Parse arXiv data
I removed test case since it had no arXiv data.  Oops. 🙄
Add class data when adding arXiv
> Get more arXiv data from AdsAbs

- Template.php
Fixes library use of NULL, where zero or FALSE is more precise
> Better use of NULL

- Template.php
So I do not have to look it up again.
> Add documentation

- Template.php
- WikipediaBot.php
Add @ to a couple I/O functions, since we handle the === FALSE outcome in the code.
> Suppress warnings that we handle with "FALSE"

- category.php
- doibot.php
- gadgetapi.php
The three APIs used $page->stuff directly.
This is all my fault for adding "protected" to those variables without looking in the php binaries
> Respect Page() protected members

- Template.php
A likelihood of 1/12 looks bad.  Change scale to 13-24 from 1-12.  Purely to make users not scratch their head when the see us doing stuff with a likelihood of one out of twelve.
> Better user output

- README.md
I do not normally submit to "master", but this is the readme that our thousands of visitors see :-)
> tiny typo on master branch

- Template.php
> Years in MLA look like issues

- DOItools.php
- Template.php
> Move query adsabs to class where called

- Template.php
Fixes AdsAbs updating api methods
- change colon to space in API key
- change http to https
301 errors with http
> Update API AdsAbs

- Template.php
- tests/phpunit/TemplateTest.php
Also fixed RIS if the page numbers are in the wrong order.
Please look at my skipping of ISSN, etc.
> Go directly to jstor RIS, skip citoid

- Template.php
Fixes http usage that will probably be turned off some day
AdsAbs already did it
> http to https

- doibot.php
Fixes bot trying to edit main page without a warning to users.
> Require a page

- Template.php
- tests/phpunit/TemplateTest.php
Failed to use page ranges from CrossRef because PHP changed != years ago with strings.
Also, had to add code to handle upgrading of page=123 to pages=123-456
> Get end pages from CrossRef

- Template.php
expanded pages=123 to pages=123-123  
String comparisons are hard.
> Fix earlier pull on page ranges

- Template.php
if It has a doi then it is published and should no longer be cite arXiv.
Discussion done
> arxiv with doi should be journals 

- Template.php
I bet travis CI does not have all the certificates installed in their PHP
https://github.com/travis-ci/travis-ci/issues/6339
> Ignore ADSABS certificate errors

- Template.php
Fixes pissed off people.  Also, there are many other ways that it might already be linked.
> Do not add Google URL

- Template.php
- tests/phpunit/TemplateTest.php
DOI is 'published' date that matches journal, etc.
> Make DOI dates overwrite Arxiv dates

- Template.php
- tests/phpunit/TemplateTest.php
> Do not add Open URL if already has PMC/arxiv

- Template.php
- tests/phpunit/TemplateTest.php
Includes a test to make sure we do not add urls
This is ready to merge I believe
> Do not add Google Books URL-part 2

- Template.php
- tests/phpunit/TemplateTest.php
Multiple databases sometimes define series and journal title differently
Includes a test now
This is ready to merge I believe
> Avoid Series and Journal names that are the same

- Template.php
- tests/phpunit/TemplateTest.php
Rejects URLs that do not resolve.
Includes a test
Ready to merge I believe
> Check Open Access URL to see if they work

- constants/parameters.php
Otherwise coauthors becomes vauthors
> Add more items to white list

- Template.php
> Change cite web to cite journal if pubmed is found

- gitpull.php
Will be run by Travis eventually; see #450
> Git pull url

- tests/phpunit/TemplateTest.php
> Dud doi now working

- tests/phpunit/WikipediaBotTest.php
Will allow pull requests to clear Travis CI
> Only test bot if !PR

- tests/phpunit/TemplateTest.php
> Skip tests that require secrets if secrets are unavailable

- tests/phpunit/PageTest.php
> Skip Page write tests if Pull Request

- .travis.yml
- gitpull.php
> Travis Build Stages

- Template.php
- tests/phpunit/TemplateTest.php
Old deprecated parameter that is empty in a lot of pages
> Remove Empty coauthor(s)

- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
Fixes Build from complaining about "risky" tests
> Make Travis think we tested something

- doibot.html
> Add waiting message do doiboth.html interface

- Comment.php
- Template.php
- constants.php
- expandFns.php
Fixes #473 .
- Remove comments from queries
- Remove parentheses from queries (not supported at present; see https://github.com/adsabs/adsabs-dev-api/issues/43)
> AdsAbs API improvements

- Template.php
Should allow Travis to complete PR checks.
> Trigger NOTICE if PHP_ADSABSAPIKEY not set

- Template.php
See https://github.com/adsabs/adsabs-dev-api/issues/43.
> Use ""s to allow parentheses in AdsAbs queries

- expandFns.php
Fixes the fact that I am easily bothered
> Format Travis logfiles as non-html

- tests/phpunit/WikipediaBotTest.php
> Neeed double quotes for linefeeds

- Template.php
- tests/phpunit/TemplateTest.php
Other Bots will just come along and remove this anyway
https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/CitationCleanerBot_3
https://en.wikipedia.org/wiki/Help:Citation_Style_1#Identifiers
> Remove ASIN, if we have ISBN

- tests/phpunit/DOIToolsTest.php
- tests/phpunit/PageTest.php
- tests/phpunit/ParameterTest.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/WikipediaBotTest.php
- tests/phpunit/constantsTest.php
- tests/phpunit/expandFnsTest.php
- tests/phpunit/wikiFunctionsTest.php
I do not know if this should be committed or not, but good to look at
> Run tests with whining

- expandFns.php
ADDED: If long is true, then print whole stack trace.
> Improve debug output

- constants.php
English  is the language of choice, but not universal.  Add a few more
> Weird journal capitalization 

- doibot.html
- doibot.php
Only noticed since the GitHub viewer flags it
> <input> ends within itself

- Template.php
As the code is currently written, you should not get here, but plan ahead.
> defensive programming

- expandFns.php
- tests/phpunit/TemplateTest.php
> strip pdf off of end of DOIs

- Template.php
I looked at the xml.  Adds one more way to find it.
> Find PMC in a new way

- Template.php
- tests/phpunit/TemplateTest.php
> recognize citeseerx URLs

- constants.php
> Add some more short words

- .travis.yml
- Template.php
Only thing that 7.1.11 failed on
> Update code for PHP 7.1.11 readyness

- Template.php
> add FALSE return code if nothing found

- Template.php
- tests/phpunit/TemplateTest.php
In the test, work is set to journal name.  By changing it to journal= we are able to then drop publisher
> Prefer journal= over work=

- Template.php
- tests/phpunit/TemplateTest.php
Might get PMC, ARXIV, HDL, etc.
> Try to use open URL access even if we already have url

- Template.php
- tests/phpunit/TemplateTest.php
ZBL
MR
SSRN
OSTI
JFM
Since we are now grabbing open access URL like crazy.  Time to clean up more URL types to make room for out open-access links.  Also, open access link might be one of these.
> Support a great deal more URL conversions

- Template.php
Just to be safe include PMC of zero
> Do not add PMID=0

- .travis.yml
- category.php
This checks things like category.php that normal test do not.
I have verified by adding some rubbish to catagory.php and the build died!
> PHP Lint all files

- Template.php
- expandFns.php
- tests/phpunit/TemplateTest.php
This fixes us from making garbage input even worse.
> Deal with URLs as Journal names

- Template.php
- tests/phpunit/TemplateTest.php
Turns out I do not know the difference of 0 and "0"
> pmid=zero case

- docs/CONTRIBUTING.md
> ## Bot output conventions

- doibot.html
Isn't HTML wonderful  🙄🤔😡
https://stackoverflow.com/questions/5195933/with-form-validation-why-onsubmit-return-functionname-instead-of-onsubmit
Also add DOCTYPE because that is the way it "should be"
> fix doibot failure to submit

- index.html
Fixes Nothing other than setting a good example for the young people today......
> Standards compliant.  Even if it is pointless

- doibot.php
this is the kind of pull one gets when on reads up on html standards over the years
> We are not actually XHTML, just HTML

- category.php
Moving towards enabling ALL warnings
> Initialize variable

- Template.php
If no bibcode or DOI, but we have arXiv, then try that before trying title.
This code is not actually being tested on travis because of lack of key
> Query AdsAbs with arXiv information

- category.php
PHP lint option was useful....
> Add Slow Mode option to category code

- Template.php
> Forget location for journals like publisher

- Page.php
> That API is unused

- Page.php
Reverts ms609/citation-bot#602
Come to think of it, it will be used soon.
> Revert "That API is unused"

- Page.php
Easier debugging and add protected to some
> explicitly declare all class variables

- Template.php
> remove trailing comma from title/journal

- constants.php
My tests that I implemented caught me not once, but twice with whitespace errors.
> Los Angeles capitalization

- Template.php
- tests/phpunit/TemplateTest.php
class is not a very useful parameter
consensus not needed for this change since we just add it less often -- not removing it.
> Only add class= to arxiv

- Page.php
> Do not treat boolean as array()

- Page.php
> remove confusing unused local variable $text

- tests/phpunit/PageTest.php
> Test empty pages

- Template.php
People enter PMC values with PMC included
> clean up PMC

- Template.php
- tests/phpunit/TemplateTest.php
No longer just delete it.  Change it to encourage better editing in the future.
> Deal with empty work= parameter better

- Template.php
> Do google books for cite web

- Template.php
> forget archive when forgetting URL

- Template.php
- tests/phpunit/TemplateTest.php
If you look in the log files, you can see that the google removal stuff is gone
> Remove extraneous google books "removals"

- Template.php
> add_if_new only if new for series & issn

- .gitignore
- Page.php
- Parameter.php
- Template.php
- apiFunctions.php
- constants.php
- constants/bad_data.php
- constants/capitalization.php
- constants/parameters.php
- constants/regular_expressions.php
- expandFns.php
- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/constantsTest.php
- tests/phpunit/expandFnsTest.php
Refactor not entirely complete, but ready for testing.
> Test integrated API searches

- constants.php
> Capitals again

- WikipediaBot.php
> Remove _talk from pages in category

- .gitignore
- .travis.yml
- Page.php
- Parameter.php
- Template.php
- apiFunctions.php
- category.php
- constants.php
- constants/bad_data.php
- constants/capitalization.php
- constants/parameters.php
- constants/regular_expressions.php
- doibot.php
- expandFns.php
- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/apiFunctionsTest.php
- tests/phpunit/constantsTest.php
- tests/phpunit/expandFnsTest.php
> Doi validation failure

- category.php
> Note user anonymity

- Page.php
- docs/ISSUE_TEMPLATE.md
- docs/PULL_REQUEST_TEMPLATE.md
- expandFns.php
> Throttle to 6EPM

- doibot.html
- doibot.php
> Support multiple pages in doibot.php

- doibot.html
- js/doibot.js
> UI slickness

- constants/capitalization.php
> Don't cap og

- gadgetapi.php
One is needed.   Second one is for the future.
> Fix GADGET_API

- tests/phpunit/apiFunctionsTest.php
> Fix implosion in adsAbsTest

- Template.php
- tests/phpunit/TemplateTest.php
> Drop user name from researchgate URLs

- Template.php
> Support “at”

- Template.php
> remove left over $this->

- Template.php
> Not html tags that end in semicolons 

- constants/capitalization.php
- tests/phpunit/TemplateTest.php
Run it all the way through code not just functions.
It did not work.  :-(
> add eJournal test-first letter is not capitalized

- Template.php
Also removes the errant template from printing in travis log files
> more consistent output

- WikipediaBot.php
process curl errors before json is done
> Split error messages for easier error interpretation

- Template.php
- apiFunctions.php
- tests/phpunit/TemplateTest.php
Had to make a new pull, since I had to change more files
> support more arXiv URLS formats

- Page.php
- tests/phpunit/PageTest.php
Even a test that works and one that the doi is not found
> Add support for plain DOI references

- Page.php
- category.php
- process_page.php
does not make us run elsewhere, but is a step in the right direction.
> Internationalization of wikipedia

- Template.php
Not using code, but update to request and URL not jstor specific
> Citoid API generalization

- process_page.php
Improve user output to be a little nicer to the new/clueless user
> make bot a little friendlier

- gadgetapi.php
If we do not change text then do not add us to edit summary
> Do not put our stamp of approval on nonedits

- Template.php
> Report bare reference conversion

- Template.php
- tests/phpunit/PageTest.php
> Use type instead of format

- Template.php
- apiFunctions.php
- tests/phpunit/TemplateTest.php
> new bad arXiv data:  pages=astro-ph/9508159

- Template.php
> Trim researchgate chapter-url too

- Template.php
And checking current build state.
> small typo

- gitpull.php
Currently the output of the git pull is repeated.  Not a big deal
> Do not echo previous commands output too

- tests/phpunit/TemplateTest.php
- tests/phpunit/apiFunctionsTest.php
I got burned by this once.  Took me a while to figure out.
> test the tests

- Page.php
- api_handlers/zotero.php
- tests/phpunit/zoteroTest.php
PHP has been failing on toolforge; this may fix it?
> Ms609 patch2

- api_handlers/zotero.php
- constants/bad_data.php
> WEB_NEWSPAPERS

- Template.php
- api_handlers/zotero.php
- constants/bad_data.php
- tests/phpunit/zoteroTest.php
> Don't add authors to web pages

- Template.php
- api_handlers/zotero.php
- expandFns.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/expandFnsTest.php
- tests/phpunit/zoteroTest.php
Fixes https://en.wikipedia.org/w/index.php?title=Mollusca&diff=prev&oldid=861484387
> Date check

- Template.php
> much cleaner code

- api_handlers/zotero.php
About half the calls to zotero in the test suite are google books
Added PLACEHOLDER just for good measure
> Eliminate useless zotero calls

- constants/bad_data.php
> More bad data filtered

- Template.php
recursive nightmare
See https://github.com/ms609/citation-bot/pull/875
> remove infinite loop

- expandFns.php
Likelihood of this not being rubbish lower than winning lottery 
Also clean up just a number code
> Reject date=-1,0,1

- Template.php
- tests/phpunit/TemplateTest.php
Doi has #page= stuff on end and should Truncate off location
> DOI urls ending in #pages=

- expandFns.php
not sure where this is coming from, but it has appeared
I assume zotero but could be date()
> Better date error handling

- Template.php
- tests/phpunit/TemplateTest.php
> MOS:ELLIPSIS

- constants/bad_data.php
Due to ["An Error Occurred Setting Your User Cookie"](https://en.wikipedia.org/w/index.php?search=insource%3A%2FAn+Error+Occurred+Setting+Your+User+Cookie%2F&title=Special%3ASearch&go=Go)
> "An Error Occurred Setting Your User Cookie"

- api_handlers/zotero.php
- tests/phpunit/zoteroTest.php
For many things the type=book but title=title not title=booktitle
> add publisher for more  books

- api_handlers/zotero.php
> Better work parameter choice

- Template.php
- constants/parameters.php
Since we add newspaper and it might already have other ones set
Since we add journal to cite encyclopedia and we get gigo
> encyclopedia & newspaper are work aliases

- Template.php
> I broke the handle code

- tests/phpunit/PageTest.php
You wrote the function, so let’s use it
> Use requires_secrets

- Page.php
> For pages with no templates

- Template.php
Cite web without URL is just wrong, but do not make worse
> Do not change work to website unless there is url

- Template.php
- tests/phpunit/TemplateTest.php
Tests added too (without being asked)
> Convert Format with URL

- constants/capitalization.php
> eLS - add to journal title list

- Template.php
> Replace title=Archived copy

- constants/bad_data.php
> 502 Bad Gateway

- api_handlers/zotero.php
- tests/phpunit/expandFnsTest.php
volume=ser.6:t.4 (1884)
where 1884 is the year
> biodiversitylibrary is not parsed well - reject volumes with parethesis

- constants/regular_expressions.php
and add warning to code
I did report this handle as non functional too
> Remove rogue handle site

- constants/capitalization.php
> ACM journals capitalization 

- api_handlers/zotero.php
- tests/phpunit/zoteroTest.php
I should have included a test last time
PHP escaping in strings is not always obvious
> Reject bad volume data

- Template.php
more common than it should be.......
> Replace title={title} with real data

- Template.php
- constants/regular_expressions.php
No more whack a mole playing with the thousand of hdl providers
> If existing hdl is in url, then do not add url

- constants.php
- expandFns.php
Old code changes them to spaces
I am not looking forward to emojis encoded doi
> Plus signs inside of dois grrrrr

- expandFns.php
- gadgetapi.php
- user_messages.php
The gadget API cannot handle this output.  It crashes the API.
> Fix gadget API

- api_handlers/zotero.php
fixes freezes
The times I choose are mostly random
> Give zotero a time-out

- Page.php
- tests/phpunit/PageTest.php
When the url title matches the url, try to expand
> Support <ref>[htt.... htt..]</ref> expansion

- expandFns.php
> Allow slow Travis builds to live

- api_handlers/zotero.php
Do not throw stuff that you do not catch
> Stop zotero errors from crashing bot

- Template.php
- constants/bad_data.php
- constants/regular_expressions.php
People are grumpy about use of newspaper= paramater
> Use work= instead of newspaper= for online news

- constants/bad_data.php
- tests/phpunit/PageTest.php
This way we can easily just use this test instead of remaking it every time
Please merge
> Save this test so we can have it standing by

- Template.php
> Do not add ASIN when ISBN is present

- DOItools.php
> &#39; Apostrophe straighten too

- DOItools.php
Probably not human being or has a name that does not split into first/last easily.
> Non human authors

- Template.php
> Fix url to chapter-url conversion

- Template.php
every time you run the bot it is going to try to add the same URL again and again and again......
> do not do work it new url is same as old url

- api_handlers/zotero.php
{{ cite book | title = Basic Neurochemistry: Molecular, Cellular and Medical Aspects | journal = | edition = 6th |author1=Olsen, R. W. |author2=DeLorey, T. M. |editor1=Siegel G. J. |editor2=Agranoff, B. W. |editor3=Albers, R. W. | location = Philadelphia, PA, USA | publisher = Lippincott-Raven | year = 1999 | url = https://www.ncbi.nlm.nih.gov/books/bv.fcgi?rid=bnchm.section.1181 | chapter = GABA Receptor Physiology and Pharmacology |display-editors=etal}}
> better journal filtering

- Template.php
- api_handlers/zotero.php
- constants/bad_data.php
Added to profoundly_incomplete() so that we do not mind lack of date.
Do not get saved date from archives.
Do not get last edited date from wikipedia
> Do not grab last edited dates some sites

- Template.php
- tests/phpunit/TemplateTest.php
https://en.wikipedia.org/w/index.php?title=User_talk:Citation_bot&oldid=867463354#Emergency_blacklist
> zenodo.org has been blacklisted

- Template.php
- tests/phpunit/TemplateTest.php
> More europepmc URLS

- api_handlers/zotero.php
- Adding YouTube to the list of domains which  should not be expanded to a {{cite web}}
- Twitter can also have www. in the URLs
> YouTube = {{cite AV media}}

- Template.php
> When adding Times newspaper, forget Times via

- Template.php
- apiFunctions.php
JSTOR does not work at this moment, but found this while debugging.
Long-term best to not be annoying
> Do not search jstor for Comments

- Template.php
Prevents having to run bot twice
> Sanitize DOI before comparing

- Template.php
> Do not add title if it matches encyclopedia

- Template.php
> Minimize changes-recognize wikiinks

- constants/capitalization.php
- tests/phpunit/TemplateTest.php
Need to to add z fur physique with umlaut messed up still
> Capitalization.  The struggle continues - OECD

- js/index.js
> javascript semi-colons

- DOItools.php
More readable now.
Only file that is just loaded with tabs (except for when it is not!)
> Fix inconsistent usage of space and tabs

- Page.php
- Template.php
Noticed it echoing in logfiles from test
> Use  report_info()

- Template.php
- tests/phpunit/TemplateTest.php
Added test that mimics the new single template interface when called with no arguments.
Found the bug.
> Fix infinite loop

- Template.php
- expandFns.php
We do this in three places so create a function.  Also add ignoring leading "the"
> Better String Comparison

- constants/bad_data.php
Just ran across while testing bot...
> journals.ametsoc.org => CANONICAL_PUBLISHER_URLS

- constants/bad_data.php
> SSRN puts invalid self-promoting data in CrossRef

- docs/CONTRIBUTING.md
wrong version in documentation
Guess who is teleworking part-time this week 🤔
> Wrong PHP version in docs

- api_handlers/zotero.php
Also make jstor regex non-capturing, since we don't capture it
> do not expand google searches

- generate_template.php
Paranoid.  Just do not want us to try to deal with bad data.  Help prevent deliberate/accidental DOS attacks.  With the current code, calling with no arguments is a DOS -- See infinite loop bug.
> Add data sanity checks

- constants/bad_data.php
- tests/phpunit/constantsTest.php
A test to make sure I never mess up again
Added "Dissertations Available from Proquest"  just got that from a url
> These constants should be lower case

- Page.php
- Template.php
- tests/phpunit/TemplateTest.php
Just like we do to google books, researchgate, etc.
> simplify google search URLS

- api_handlers/zotero.php
- constants/bad_data.php
Also drop researchgate code that never helped
> Convert blocked hosts to a const array

- Template.php
- expandFns.php
- tests/phpunit/TemplateTest.php
I have obviously been looking at dead dois
Do not want to drop urls since they include page and chapter information after DOI
> Special code for 10.1093 DOIs

- constants/bad_data.php
Version user reported had period
> BAD_AUTHORS add some stuff from Russian Journals

- Template.php
And only if PMC actually works of course.
Highly recommend reviewing this diff with white-space changes disabled
> Forget PMC URLs, if PMC is already sset

- Template.php
- tests/phpunit/apiFunctionsTest.php
Fixes things such as http://www.worldcat.org/title/dictionary-of-entomology/oclc/1038886039
> worldcat might have title in URL

- expandFns.php
- tests/phpunit/TemplateTest.php
Did not loop over array
Added question mark to list while there
> Stupid bug

- Template.php
> Do not change existing linked data

- Template.php
> Remove trailing via= from sciencedirect.com urls

- Template.php
a lot of jstor doi's do not resolve
> Forget DOI that is really jstor, if it is broken

- Template.php
- tests/phpunit/apiFunctionsTest.php
https://www.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=pubmed&tool=sumsearch.org/cite&retmode=ref&cmd=prlinks&id=16032283
> Add more entrez support

- expandFns.php
German "the" vs "Des" as in design
> des vs. Des

- Template.php
Some searches have numbers in them.
Also add some slashes to escape some periods
> Don't convert searches with ID to pmid or pmc

- Template.php
> Class is now deprecated in {{citation|}}

- WikipediaBot.php
currently just echos “Failure”
> Better error message

- Page.php
- tests/phpunit/PageTest.php
> Add pipe to divide parts of edit summary

- apiFunctions.php
- tests/phpunit/TemplateTest.php
> Prefer DOI information to arXiv data

- Template.php
Only if a single dash with numbers only
> Deal with spaces in issues & pages (numbers only)

- Template.php
j.string style.   
I have only seen letters
> Support more jstor journal stable styles

- api_handlers/zotero.php
@ms609 I accidentally lost case insensitivity during improvement
> Case insensitive

- Template.php
- tests/phpunit/TemplateTest.php
> convert volume to issue in zookeys.

- get_linked_pages.php
I looked more carefully at other examples 
Also will not include links to things like jstor, doi, isbn, etc.
> Make linked pages work

- api_handlers/zotero.php
report, bookSection, magazineArticle, and blogPost.
> add more types and make consistent

- Template.php
Some have date=2001 set instead of year=2001.  We should use that information
> Better bibcode matches-years

- Template.php
We adding web newspapers, we left website= set.
> Avoid work/website alias error

- Template.php
> Verify bibcodes year before adding

- Template.php
- apiFunctions.php
- tests/phpunit/TemplateTest.php
> Expand book based bibcodes

- apiFunctions.php
http://adsabs.harvard.edu/abs/1982MSS...C03....0H changes to another bibcode and the whole query results are wrong
> detect corrupt big queries

- Template.php
We sometimes get things that are not right
We should not add bibcodes if the title does not match
> Verify that title matches in bibcode search

- Template.php
This is obviously some hand waving math and estimating
> Avoid adding bibcodes for book reviews to books

- Template.php
Fix Deim_Zubeir Reported errors
> Clean up titles before querying adsabs

- api_handlers/zotero.php
knowing url is useful 
I thought this would help with Deim_Zubeir (it didn't but still good to add).
> Easier debugging

- constants/bad_data.php
> Add NASA website to blacklist

- Template.php
Mostly add documentation.
Add extra code in case arXiv leads to journal
> Improve process()

- constants/bad_data.php
Saw:
Sorry. The page you are looking for does not exist
> add 'does not exist' to bad titles

- api_handlers/zotero.php
If the remote page is not found, avoid discussing JSON
> Better error output

- Template.php
We currently jump to the book code before we make sure that the title and year are reasonable.  
There is a single book in the adabs database with Journal=Genetics set.  So, that entire journal matches this book.
http://adsabs.harvard.edu/abs/2001gpm..book.....L
> Do book code after data verification step

- expandFns.php
- tests/phpunit/expandFnsTest.php
Just looking at code coverage output again
> More ExpandFns tests

- apiFunctions.php
- tests/phpunit/TemplateTest.php
Add two new Regex and three new tests.
FYI: my teleworking part-time for break has come to an end
> More parse_plain_text_reference

- constants/bad_data.php
The things one notices while using the bot
> Add geoscience publisher

- Template.php
- tests/phpunit/TemplateTest.php
Split two unrelated tests and and some more sub-tests
> improve tests slightly

- DOItools.php
- Parameter.php
- Template.php
- constants/bad_data.php
- tests/phpunit/TemplateTest.php
Forgot this one
add a comment in both locations pointing to the other location 
also add  CITATION_BOT_PLACEHOLDER_COMMENT to Template.php
The orginal tests I committed were not valid :-(
> Do not mess with dashes in [// URLs and comments

- Template.php
- apiFunctions.php
> Use public functions, not protected

- DOItools.php
- Template.php
Put same code in one place and add dashes
> use titles_are_dissimilar()

- tests/phpunit/WikipediaBotTest.php
Standardize on one location for checking that
Single point of failure/success.
> Use requires_secrets()

- apiFunctions.php
- tests/phpunit/TemplateTest.php
> More arXiv Regex

- Template.php
- api_handlers/zotero.php
- expandFns.php
- tests/phpunit/TemplateTest.php
> Add jstor too for dois

- Page.php
- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
we some way to make this be a checkbox in the GUI
Beware of pitchforks 
I think when submitting a single page we need another option like “slow” to turn this on.   Perhaps only in gadget API so people always know who did it.
> We need this to not be the default

- Template.php
- tests/phpunit/TemplateTest.php
> More jstor proxy:www-jstor-org urls

- Template.php
- apiFunctions.php
Never a good idea.  Probably would be best to follow the URL and update it, but that's a lot of extra work for a URL that wiley will redirect for the user
> Do not add/use DOI's that are just an ISSN

- constants/bad_data.php
- constants/capitalization.php
> Add more publishers

- Template.php
- api_handlers/zotero.php
- tests/phpunit/TemplateTest.php
They are valid, so add them. 
Just don’t use zotero either
> More DOI only ISSN code

- Template.php
The exact same check is done several lines higher
> Remove duplicate check

- Template.php
We do not actually use the return value!!!!!!
> We were NOT searching CrossRef for DOIs

- constants/bad_data.php
Not random, this is yet another change noticed during the ISSN only DOI problems fixing
> Wiley Online Library is a bad title

- Template.php
- tests/phpunit/TemplateTest.php
> do not change to cite journal, if just ISSN DOI

- api_handlers/zotero.php
- tests/phpunit/TemplateTest.php
Since we do exact match, cannot add Book and Title strings together and then compare.
Also, check journal title too, in case it is bad too
> Better bad data detection 

- Template.php
- tests/phpunit/TemplateTest.php
> Avoid false positives in OA search

- api_handlers/zotero.php
Avoids this kind of tedious and pointless case where we fail a hundred times in a row:
https://phabricator.wikimedia.org/P8064
> Stop hammering Zenodo for generic URLs when it keeps failing

- Template.php
- api_handlers/zotero.php
> more aliases that mean the reference is complete

- DOItools.php
- Template.php
- api_handlers/zotero.php
- tests/phpunit/apiFunctionsTest.php
It is a nice little function, we should use it.  I am not so aggresive as to use it to "tidy()" human input data, but can tidy our stuff.
> Use truncate_publisher

- expandFns.php
> Match short forms

- Template.php
- api_handlers/zotero.php
The tide seems to be turning on this issue sadly.
> Pitch Fork Control

- Template.php
this has happened — very painful to Travis
> NEEDED SOON: Continue when BIBCODE blocks us

- Template.php
- tests/phpunit/TemplateTest.php
the RFC went our way mostly, but not quite enough for a bot to do the work
> Red Alert:  Location and publisher gets to stay

- WikipediaBot.php
- tests/phpunit/WikipediaBotTest.php
- $xml was used without being set (should have been $res)
- The data structure was wrong too
- Even the test was wrong
> Done: Fix redirect_target()

- Template.php
Regex used where dash should be used
> Done: Wrong parameter used

- Template.php
Just add optional leading (?:vol. |) to regex
> Done:  Also support case Vol. 23, No. 23423

- DOItools.php
Tiny speedup
Get us closer to user based oauth by removing false references to oauth 
@ms609 Lots of little code changes this week
> Done: Remove unused include

- gadgetapi.php
Fixes nothing, other Han subtle code style differences
> Done: More consistent coding style

- Template.php
One more format= thing to drop (very common in cite arXiv)
> add [[pdf]] to list of PDF identifiers

- Page.php
> Undo all the way if no robots

- Template.php
As long as there is a DOI/PMC/PMID and no URL
> Remove via= for common publishers

- Page.php
- Template.php
- tests/phpunit/TemplateTest.php
Fully do the chapter-url then the url.  Old code would not drop stuff if it was used.  Also, did not simplify URLS.
@ms609 I included a test!
> Treat url and chapter-url at same time better

- category.php
- tests/phpunit/TemplateTest.php
> VERY HIGH PRIORITY:  Use HTML output on web

- Template.php
> LOW PRIORITY BUT EASY: remove unused code that generated pitchforks

- Template.php
Otherwise you have to run bot a second time to get this to happen.
> MEDIUM PRIORITY:  add PMID after adding PMC

- Template.php
It is an alias for citation.  
This went away over a decade ago: you were part of it.
> MEDIUM PRIORITY:  template cite is a real thing-convert it

- Page.php
- tests/phpunit/TemplateTest.php
I do not want to start capilizing etc. this template, but this is one thing we can do.
> LOW PRIORITY:  straighten quotes in magazine parameter

- Template.php
- tests/phpunit/TemplateTest.php
Makes searching the code much easier
Sick and tire of seaching for add_if_new("journal" and add_if_new('journal'
> LOW PRIORITY:  more consistent

- Template.php
- expandFns.php
Blah/Blee is common in journal names
> MEDIUM PRIORITY: Capitalise after slash even without space

- Template.php
> Rename existing via to publisher/journal/etc

- gadgetapi.php
Avoid BOTPOL.
You know you are good, when people start considering this a worthwhile bug.
> Use the word tool, when not running as bot

- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
fake-url.com is in Whois
Best to be 100% bogus
> consitent fake url format

- constants/capitalization.php
One is a journal that capitalizes “an”
> Capitalization

- Template.php
also add support for number cleanup too (same as issue)
Also fixed bug where year could be used to set issues=value, if year started with zero
> Remove No. from issue=

- Template.php
> treat "post" special

- constants/parameters.php
I added code that does conversion, but forget to process it.
> we process just 'cite' also

- category.php
Simpler to read and faster to run?
Fixes #1441, which does not seem to have been resolved in the production code – possibly just because the server has not been updated recently?
> Use substr in place of preg_match

- tests/phpunit/WikipediaBotTest.php
Rather than weird error messages
> catch fetch() error in test suite

- Template.php
> Wrong function called

- Template.php
> ExplIcit caste to integer from single char string

- Template.php
> Passed wrong parameters

- category.php
Just text given with no dash option
Clear dash option once a dash-dash option is given
Yes, someone got a new static code analysis tool
> deal with invalide command line input

- Template.php
In an _extreme_ case, this would be needed.
> Initialize more variables

- constants/capitalization.php
> BJOG journal acronym

- api_handlers/zotero.php
- category.php
- process_page.php
Do not depend upon all the entry points setting the variable.
> Less usage of globals

- DOItools.php
- tests/phpunit/DOIToolsTest.php
> Add test and deal with GIGO Better

- DOItools.php
- WikipediaBot.php
That exception type does not get thrown by the library we use
> Need to catch correct exception

- DOItools.php
> Use more exact type

- Template.php
Code will not change output, but we future proof and PHP gets more and more type happy
> Booleans - use right operators 

- DOItools.php
- Template.php
- expandFns.php
This is what NULL currently yields.
> Do not depend upon defaults that might shift

- Template.php
> Empty strings and other things == false. Be exact.

- Page.php
- Template.php
- apiFunctions.php
- constants/math.php
- generate_template.php
{{cite journal | last=Berentsen | first=Sigbjørn | last2=Sundic | first2=Tatjana | title=Red Blood Cell Destruction in Autoimmune Hemolytic Anemia: Role of Complement and Potential New Targets for Therapy | journal=BioMed Research International | publisher=Hindawi Limited | volume=2015 | date=2015-01-29 | issn=2314-6133 | pmid=25705656 | pmc=4326213 | doi=10.1155/2015/363278 | pages=363278}}
vs
{{cite journal | last=Berentsen | first=Sigbjørn | last2=Sundic | first2=Tatjana | title=Red Blood Cell Destruction in Autoimmune Hemolytic Anemia: Role of Complement and Potential New Targets for Therapy | journal=BioMed Research International | publisher=Hindawi Limited | volume=2015 | date=2015-01-29 | issn=2314-6133 | pmid=25705656 | pmc=4326213 | doi=10.1155/2015/363278 | pages=1–11}}
The bot …
> Prefer article number to pages 1-12

- Page.php
- Template.php
- WikipediaBot.php
- expandFns.php
We never load env.php in some code paths.
expandFns.php continues to become the one-stop-shop for all our interfaces
> Need adsabs Keys in gadget and generate_template API too

- process_page.php
> Flush before explicit HTML code

- WikipediaBot.php
I added them a while back, but never used them
> we will not need these headers afterall

- category.php
Put:
Anonymous user. Add &user=MyUserName to URL to sign the bot's edits
and 
Activated by user ....
After html tags so they are formatted properly.
> Start output after <html>

- constants.php
- tests/phpunit/README.md
we aren’t adding and new ones any time soon
Static analysis tools really hate these things too
Also make finding usage with search easier
> Remove glob

- README.md
- gitpull.php
@ms609 What did I do that keeps breaking GIT???
> list what files are changed for easier error understanding 

- Template.php
- tests/phpunit/TemplateTest.php
Otherwise it is almost always some thing like Journal of Organic [[Chemistry]]
> Only add title-link if a large part of title text

- Template.php
- tests/phpunit/TemplateTest.php
If the title is one of these, then just remove the square braces
> Fix messed up cases.  [[sdfsad] or [dsfasdf]]

- generate_template.php
> HTML 5 - just because

- expandFns.php
> convert <em> to <i> on incoming text

- get_linked_pages.php
> Ignore disambiguation

- generate_template.php
> Html encode output

- Template.php
- tests/phpunit/TemplateTest.php
If the citation has a DOI, and the doi agrees with one of them, then change the other one.
Even a test case.
> Fix volume=issue

- gitpull.php
- phpunit.xml.dist
- unlock_git.php
@ms609 Since we are gooned again.
> Implement file locking in git pull

- Template.php
do not override human choice to do so
> special code for title

- constants/bad_data.php
> amjbot.org

- Template.php
- tests/phpunit/TemplateTest.php
> add testCleanUpTemplates()

- Template.php
also, reduce dropping ISSN, since some journals/magazines are obscure.  VERY obscure
> convert worldcat to issn

- constants/regular_expressions.php
> dataverse.scholarsportal.info hdl

- constants/parameters.php
> cite publication is cite book

- constants/bad_data.php
> association is not a human

- constants/bad_data.php
> gsapubs.org

- constants/bad_data.php
> More non humans

- constants/capitalization.php
> obviously French words

- Template.php
> Remove blank via too

- constants/parameters.php
> Rename cite article

- Template.php
- constants/parameters.php
> Cite website

- Template.php
> Europe PMID

- Template.php
> Add more types to add if new

- Template.php
> Reject non-functional Oxford DOIs

- Template.php
> Do not rename templates with 10.1093 dois

- constants/capitalization.php
> USA AND US

- Template.php
> Preserve white space

- Template.php
> Deal with empty author

- constants/capitalization.php
> APS Division

- Template.php
> Update API and API name

- Template.php
Linked chapter or trans-chapter exists at all
> Do not convert url to chapter-url in some cases

- Template.php
> don't convert google books to chapter without page

- constants/capitalization.php
> (online ed.)

- constants/capitalization.php
> OBVIOUS_FOREIGN_WORDS

- Template.php
- apiFunctions.php
Contributes to #1769 
- Search for results that match any available identifier
To do: 
- Handle cases where multiple conflicting identifiers exist, and `$result->numFound > 1`.
> Adsabs identifiers

- README.md
- env.php.example
- Updated README.md to remove outdated info and explain the env.php file.
- Added env.php.example file.
> updating README and adding env.php.example

- zotero.php
Reverts ms609/citation-bot#1787
> Revert "remove trailing ?via%3Dihub from urls when compare"

- constants/bad_data.php
> CUR_TITLE Is bad title

- constants/bad_data.php
> WordPress › Error Is bad title

- apiFunctions.php
Reverts ms609/citation-bot#1801
> Revert "DEBUGGING"

- WikipediaBot.php
- env.php.example
- setup.php
Reverts ms609/citation-bot#1817
> Revert "split tokens"

- authenticate.php
Reverts ms609/citation-bot#1823
> Revert "debug"

- category.php
- process_page.php
> Fix user????

- Template.php
- expandFns.php
The changing of if/then indents restulted in all finds being dropped.
> Fix bug introduced in #1771

- Page.php
- constants/parameters.php
Just URL cleanup for thesis and press release, no capitalization
> TEMPLATES_WE_BARELY_PROCESS

- Template.php
> Remove search engines from via

- Template.php
> fixed bugs in commented out code

- apiFunctions.php
> Truncate CR titles at roman numerals before check

- Page.php
- Template.php
> Less capitalization of UTF-8 Stuff

- expandFns.php
> Standardize strings when comparing

- zotero.php
> IEEE urls that match doi

- Template.php
- tests/phpunit/zoteroTest.php
- zotero.php
> better IEEE

- Template.php
> pqdlink and pqdweb are both used

- zotero.php
> Coteceerx sdata

- Template.php
- tests/phpunit/TemplateTest.php
> add archive dates

- Template.php
> Remove proxy from ScienceDirect URL

- zotero.php
> drop invalid science direct URLS

- Template.php
> handle proquest urls with abstract/fulltext

- Template.php
> avoid extraneous bibcode searches for now

- Page.php
> fix last edit

- Template.php
> Tidy google  dates

- Page.php
> Proxy code was evil

- expandFns.php
> Do ranges sooner

- Page.php
> remove a man code

- Template.php
> Another proxy

- constants/bad_data.php
> more publishers

- expandFns.php
> Ignore  (Clifton, N.J.) in journal titles

- apiFunctions.php
> support Thesis Data from dx.doi.org

- Template.php
> Do not add a URL that already exists

- Template.php
> Converting URL to ProQuest parameter

- zotero.php
> archive.org likes to call stuff books.

- Template.php
ISSN and ISBN can end in X.
RIS data might be a book, not a journal
ISSN RIS data might be an ISBN actually
> Better RIS and EndNote code

- .user.ini
- authenticate.php
> One week is long enough

- Template.php
> typo meant some urls were not forgotten

- Template.php
Will clean up after other pulls are done--did not want to generate a conflicted pull straight from the start
> Use doi_works instead

- Template.php
- constants/regular_expressions.php
> Google Books URL

- Template.php
> Other bots check this

- Template.php
- tests/phpunit/TemplateTest.php
> Webcitation dates

- constants/capitalization.php
- expandFns.php
> Italian dell'xxx words

- Template.php
> No international characters in type=

- Template.php
> None is special

- constants/capitalization.php
> ACS, ISME caps

- WikipediaBot.php
> Only want to visit pages in the main namespace

- Template.php
> Forget links to Reuter’s

- .user.ini
> Do not name cookies

- .user.ini
- Page.php
> remove debug

- zotero.php
> Urls ending with short or long

- Template.php
> one more jstor url format

- DOItools.php
> Replace fewer quotes

- constants/capitalization.php
> Algebra i Analiz

- Template.php
> Work is often incorrectly put in publisher

- Template.php
- constants/bad_data.php
> More JSTOR RIS formats

- constants/capitalization.php
> Non-English word

- tests/phpunit/zoteroTest.php
- zotero.php
> Disbarred MR

- apiFunctions.php
- tests/phpunit/PageTest.php
- tests/phpunit/apiFunctionsTest.php
> ARXIV broke!!!

- tests/phpunit/apiFunctionsTest.php
> Turn test back on

- zotero.php
> More journal website

- constants/bad_data.php
> Bad titles

- Page.php
- tests/phpunit/PageTest.php
Add a missing space in the edit summary
> Missing space in edit summary

- constants/bad_data.php
> Russian Ой! error title

- Page.php
- gadgetapi.php
- tests/phpunit/PageTest.php
Add a missing space in the edit summary.
> Another missing space in edit summary

- Template.php
- tests/phpunit/zoteroTest.php
> don't lose work

- tests/phpunit/TemplateTest.php
> Remove tests that google does not seem to support

- constants/bad_data.php
> More series

- phpunit.xml.dist
> Some of this

- setup.php
> Better comments

- README.md
- tests/phpunit/DOIToolsTest.php
- tests/phpunit/expandFnsTest.php
> Sorting tests

- Template.php
- phpunit.xml.dist
- tests/testBaseClass.php
> code coverage-even more

- apiFunctions.php
- tests/phpunit/TemplateTest.php
> support bioRxiv better

- Parameter.php
- Template.php
- tests/phpunit/ParameterTest.php
> better code - style and ordering 

- phpunit.xml.dist
- tests/testBaseClass.php
> Better PHP Unit

- WikipediaBot.php
> Debug  WikipediaBot.php

- tests/testBaseClass.php
> Tests back on 

- tests/phpunit/zoteroTest.php
> More tests

- .travis.yml
- Template.php
- tests/phpunit/TemplateTest.php
- tests/testBaseClass.php
> More code coverage of bad input data

- Template.php
- tests/phpunit/TemplateTest.php
- tests/testBaseClass.php
> Remove unused code and add tests and fix found bugs

- tests/phpunit/TemplateTest.php
- tests/testBaseClass.php
> Clean up tests some - still some TODOs left

- tests/testBaseClass.php
> Debug code coverage more

- setup.php
- tests/testBaseClass.php
- zotero.php
> $BLOCK_ZOTERO_SEARCH

- tests/phpunit/TemplateTest.php
> split tests

- tests/testBaseClass.php
> Turn Zotero tests back on

- Page.php
> Help garbage collector out a lot

- Template.php
> add_if_new is much better

- Template.php
> Minimum of 4 digits

- Template.php
- tests/phpunit/TemplateTest.php
> Much improved floating text conversion

- Template.php
- tests/phpunit/TemplateTest.php
- tests/testBaseClass.php
> Code coverage and remove unreachable code

- apiFunctions.php
- tests/phpunit/TemplateTest.php
> Remove outdated unused code and test that no longer works because DOI died

- tests/testBaseClass.php
> done for the day

- apiFunctions.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/apiFunctionsTest.php
- tests/phpunit/zoteroTest.php
> Code coverage

- apiFunctions.php
> Code coverage and code cleanup

- apiFunctions.php
- tests/testBaseClass.php
> Bibcode bug

- Template.php
> Clean up Open Access URL code

- constants/parameters.php
> More dead parameters 

- Page.php
> do more IEEE

- Template.php
> more pages/page clean-up

- Template.php
> be smarter about archive.org book urls

- .user.ini
- WikipediaBot.php
- authenticate.php
> one day extension every day

- WikipediaBot.php
- tests/phpunit/apiFunctionsTest.php
> Not a minor edit

- Template.php
- tests/phpunit/TemplateTest.php
> Links in author seem to work now COINS

- Template.php
- tests/phpunit/TemplateTest.php
> Fix title links

- Template.php
> Minor typo

- category.php
> Add link back

- Template.php
- constants/bad_data.php
- tests/phpunit/TemplateTest.php
> proquest ebooks

- expandFns.php
> better title match - spaces optional

- tests/phpunit/TemplateTest.php
> Issn works again

- Template.php
> cast some variables

- Template.php
- tests/phpunit/TemplateTest.php
> simpler code

- Template.php
> Do not prioritize preprints over real copies

- Template.php
> Special code for BBC

- Template.php
> add even more types

- NameTools.php
- tests/phpunit/NameToolsTest.php
> format_multiple_authors

- Template.php
- tests/phpunit/PageTest.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/apiFunctionsTest.php
- tests/phpunit/expandFnsTest.php
- tests/phpunit/zoteroTest.php
- tests/testBaseClass.php
> get() return empty string instead of null

- apiFunctions.php
> Types at 100%

- Template.php
> add types to tidy_parameter()

- Template.php
- apiFunctions.php
> add return type to query_crossref()

- Template.php
- WikipediaBot.php
> Casting of the obvious

- .travis.yml
- README.md
- docs/CONTRIBUTING.md
> Tool server is 7.3 now

- category.php
- psalm.xml
> Test suite improvement

- authenticate.php
> Remove unneeded code-flushed on exit automatically 

- authenticate.php
> localize all header() calls

- WikipediaBot.php
> Code coverage ignore

- linked_pages.php
> Duplicate include

- tests/phpunit/TemplateTest.php
> Disable failing test for now

- zotero.php
> I did not understand globals right

- tests/testBaseClass.php
- user_messages.php
> VERBOSE not needed anymore

- tests/phpunit/gadgetTest.php
> Fix Travis log files

- gadgetapi.php
- tests/phpunit/GenTemplateTest.php
- tests/phpunit/gadgetTest.php
> Better testing

- Page.php
- Template.php
- WikipediaBot.php
- Zotero.php
- apiFunctions.php
- expandFns.php
- linked_pages.php
- tests/phpunit/PageTest.php
- tests/testBaseClass.php
> Set curl agent

- authenticate.php
> That should error out

- Template.php
- tests/phpunit/TemplateTest.php
Reverts ms609/citation-bot#3392
> Revert "Do not 'fix' wikipedialibrary"

- tests/testBaseClass.php
> all on, but zotero

- Template.php
> Casting more

- authenticate.php
> Better Regex

- apiFunctions.php
- tests/phpunit/apiFunctionsTest.php
> Add a time out

- .travis.yml
- authenticate.php
- user_messages.php
> Add taint test - mostly to find unescaped HTML

- .lighttpd.conf
- .user.ini
- Template.php
- Zotero.php
> better time-outs

- Zotero.php
- tests/phpunit/TemplateTest.php
> Drop more proxies

- Template.php
- tests/phpunit/TemplateTest.php
- tests/testBaseClass.php
> Stop hash removal

- Page.php
> Throttle is the right thing

- apiFunctions.php
- setup.php
> Save memory

- setup.php
- user_messages.php
> flush better

- .lighttpd.conf
- Template.php
- expandFns.php
- php_info.test
- tests/phpunit/TemplateTest.php
> php_info.test & a few text clean ups

- constants/capitalization.php
> ische Words

- Template.php
> Better non-English detection

- Template.php
> Remove underscores from template names

- Page.php
- Template.php
- Zotero.php
- apiFunctions.php
> Standardize pointer notation

- .phan/config.php
> Better phan config file

- Template.php
> Fix modifications code

- category.php
- linked_pages.php
- process_page.php
- setup.php
> add check_overused()

- tests/phpunit/CrashTest.php
- tests/phpunit/PageTest.php
> split out test

- tests/phpunit/CrashTest.php
- tests/testBaseClass.php
> Put bad pages in headers

- tests/phpunit/GenTemplateTest.php
- tests/phpunit/NameToolsTest.php
- tests/phpunit/PageTest.php
- tests/phpunit/ParameterTest.php
- tests/phpunit/TemplateTest.php
- tests/phpunit/WikipediaBotTest.php
- tests/phpunit/apiFunctionsTest.php
- tests/phpunit/constantsTest.php
- tests/phpunit/expandFnsTest.php
- tests/phpunit/gadgetTest.php
- tests/phpunit/zoteroTest.php
> Skip all other tests when looking at bad pages

- Template.php
- tests/phpunit/TemplateTest.php
> More date stuff

- WikipediaBot.php
> Add option to edit as user back in, but defined to FALSE

- Template.php
> drop more URLs when there is an automatic title link present

- gadgetapi.php
- user_messages.php
> Deal with new Taint test added to psalm

- constants/bad_data.php
> Add HOSTNAME_MAP for ibm.com & ieee.org

- Template.php
- tests/phpunit/TemplateTest2.php
Too crazy to not test out first
> Clean up links

- README.md
- expandFns.php
- phpstan.neon
- setup.php
An option to save output to files rather than sending to Wikipedia.
There is a --savetofiles command line parameter.
> An option to save output to files rather than sending to Wikipedia

- tests/phpunit/expandFnsTest.php
fixed error in testVariousEncodes5
> fixed error in testVariousEncodes5

- apiFunctions.php
Report message on ADS API rate limit
!Need to retry after 28715s (07:58:35). Rate limit resets on 2023-12-20 12:41:55 UTC.
> Report message on ADS API rate limit

- apiFunctions.php
> comments sruc

- README.md
This pull request is a clarification on the structure of the bot in the README.md documentation. The text about the role of env.php and setup.php in the bot structure was unclear.
This pull request does not fix any code: this is a change of documentation in the README.md file.
The clarification proposed aids new users: by specifying that `env.php` defines configuration constants and can be created from env.php.example, new users are given clear guidance on how to set up their environment; mentioning that `setup.php` sets up the necessary functions and usually doesn't need modification helps users focus on the files they need to interact with.
> A clarification on the structure of the bot in README.md

- .github/workflows/trivy-analysis.yaml
A GitHub action that scans the repository for vulnerabilities, misconfigurations, secrets, and license issues. Detects vulnerabilities in dependencies and configuration files. Identifies potential license issues in dependencies. Uploads scan results to the GitHub Security tab for easy review and tracking.
> Trivy analysis
