ms609/citation-bot

Parameter.php
README.md
Template.php
tests/phpunit/ParameterTest.php
tests/phpunit/README.md

* Fix bug where an author param with no value would block author lookup
* Stop parameter-parsing regex from putting newlines before the added value
* Add automated tests for Parameter.php, handle initial Unicode space

Fix whitespace and author param handling, add automated tests for Parameter.php

---

Template.php

* Remove special case for display-authors when 9 authors are present
from Template::tidy()
* Misc. typo and style fixes (braces, one semicolon per line...)

Remove special case for display-authors=9, misc. style fixes

---

Template.php

We then count on format_title_text to clean up.  
I worry that MB_CASE_TITLE would change ZooKeys to Zookeys, if pubmed had it right for a change.

pubmed does not believe in capitalization often

---

Template.php

Unless of course they are next to each other.
This avoids changing 1970-10-7 to invalid date 1970–10–7 (really should not be in year, but date).
This also avoids changing 1-4–1-7 to 1–4–1–7 (page 4 to seven of section 1) .
This still changes if it has -- (of course 1-4--1-7 will get hosed still).

don't upgrade dashes if more than one

---

tests/phpunit/TemplateTest.php

Fixes incorrect test
- Make the test check the right values
- ISBN 13 is formated 978-########, not 978#######
-

forgot dashes in ISBN13

---

expandFns.php

This is necessary for doibot.php to run properly. It's been manually patched on citations-dev.

uncomment mysql.login inclusion

---

Comment.php
Page.php
Template.php
constants.php
tests/phpunit/ParameterTest.php
tests/phpunit/TemplateTest.php
tests/phpunit/constantsTest.php

Makes it easier to search for placeholders by standardizing text to:
CITATION_BOT_PLACEHOLDER_XYZ

standardize placeholders

---

Template.php

Fixes inconsistency in using URLS.  
When we find a DOI, get rid of URL and add DOI.

Forget dx.doi.org URLS when getting DOIs from them

---

Page.php
README.md
gadgetapi.php
tests/phpunit/TemplateTest.php

Fixes Gadget API.
Bot sends this when processes page with simply "MyText":
[15:36:43] Processing page ...
{"expandedtext":"MyText","editsummary":"\/* Testing *\/  | [[WP:UCB|Assisted by Citation bot]]"}
Leads to error on wiki side because of processing page line is not valid json:
SyntaxError: JSON.parse: expected ',' or ']' after array element at line 2 column 4 of the JSON data
I was confused about cause.  Turns out that HTML had nothing to do with it.
This turns on the eating of the buffer sooner.

Fix Gadget API-Do not echo stuff to wikipedia

---

tests/phpunit/TemplateTest.php

Instead of "either or", do "both and".
Have an encoded and non-encoded test
Made them separate tests so that the first one failing does not stop the second one from trying.

Both encoded and non-encoded Jstor SICI tests

---

Template.php
constants.php
credentials/crossref.login
tests/phpunit/TemplateTest.php

Fixes:   ISBNDB charges too much,  so use Google to process ISBN

Expand ISBN, LCCN, OCLC with Google API

---

gadgetapi.php

When gadget API fails, we can grab debug from json.
Maybe we should always send it back???

Add debug option to gadget API

---

Template.php
expandFns.php
tests/phpunit/TemplateTest.php

Fixes existing wiki-linked names getting formatted.  We just leave as-is.

Do not reformat Wiki-linked journal names

---

Template.php
constants.php

Fixes the ever growing list of publisher endings getting out of control in code base by making it an array of publisher endings.  Because we use "explode()" we know that there is a space in front of them, so we do not have to worry about some ones last name being "Splinc" being caught as "inc".  If your last name happens to be "magazines" or "inc", then sorry.

Store publisher endings in an array, not a bunch of if statements

---

Template.php
tests/phpunit/TemplateTest.php

Based on the XML data: sometimes citoid just reads it as a website, and misses that it is a journal
Code now has jstor URL that does not redirect (adds on &seq=1 kind of stuff).  I think this should greatly reduce the failures.
Code now checks for "not found" as a title.
If failure, code retries with slightly different URL to make sure Citoid does not cache answers
Test now complains -- if you read logfile -- but does not bomb out.

Deal with Citoid failures

---

doibot.php

It does not matter in this case, but good coding means we should swap it.
$this = true;
$that = false;
$truthiness = $this and $that;
$truthiness is true in the above case. :-( because "=" evaluates before "and"
And now I present you will the pickiest pull request ever........

Better operator choice

---

tests/phpunit/TemplateTest.php

Adds test to make sure we do not at some time in the future accidentally start processing random cite templates.  This is defensive programming.  I just do not want in the future an errant semi-colon or bracket cause us to suddenly start modifying cite patent or something similar.

Do no touch unknown templates

---

Template.php
tests/phpunit/TemplateTest.php

Adds test to check for proper handling of incomplete templates.  Existing code tried to access non-existent array when a citation template had zero parts to it.

Bot now handles empty templates better

---

category.php

I was just looking for $a[]= stuff in source code and I found this.
Just static analysis; not based upon a crash or anything. 
error_reporting(E_ALL^E_NOTICE); means this change is not actually needed, but makes for better code.

initalize expected user input to NULL

---

tests/phpunit/wikiFunctionsTest.php
wikiFunctions.php

Pass back empty array instead of NULL, when code fails - bug fix.
Also add test to verify that get_prefix_index does does not pass back anything if you ask for something that there are zero of.  Existing test just makes sure you get the item you want; while this test makes sure you do not getting extra stuff back.
This is from just looking for abc[]= stuff that might end up empty

verify get_prefix_index does not return wrong stuff

---

docs/CONTRIBUTING.md

GitHub does not re-direct old links
Guess who’s wife had Jury Duty and was stuck at home with little to do.

Outdated GitHub link

---

phpunit.xml.dist

Fixes category.php being flagged as no code coverage.
It is a program that connects humans to the bot, not the bot.
Really hard to test without doing a bunch of real edits.

do not coverage test category.php

---

tests/phpunit/TemplateTest.php

Fixes tests not matching real world
You have to run tests as a Page() for them to match what happens on Wikipedia.
After running them as page use Template() to access them
Some tests fail because of this, but that is good to know.
This is included in the big pull but it can stand alone

Fix all tests

---

tests/phpunit/wikiFunctionsTest.php
wikiFunctions.php

Empty categories return a bogus page of name ‘ ‘
This changes that to an empty array()
I noticed that the category script was doing one “page” even for empty categories

Return empty array instead of array with one bogus element

---

Comment.php
Page.php
Template.php

Fixed unused variables.
Also, $page would have to be set with a pointer to actually work anyway.
This is all leftover from the old Item() class, I think.
The red X on the code coverage is because the code coverage base and the dev code base are so different that a fair comparison is hard, I think

Remove unused variables

---

Page.php
Template.php
tests/phpunit/TemplateTest.php

Within Page() all templates are replaced. Thus there are no internal templates. This code sets the internal template list to match the global list of templates.
IT ACTUALLY WORKS 
I had to create a whole slew of tests to make sure this did not break stuff.
When merging this you definitely want to chose the forget all intermediate modifications option

fix templates within templates

---

Template.php
constants.php
tests/phpunit/TemplateTest.php

Pages of "arXiv:1711.02260" is returned along with volume of "1711" and journal of  "arxiv e-prints".

Some bibcode data is bad

---

Template.php

Bug fix:  A SICI might not resolve and would get passed on and parsed as stable url and that’s the wrong number.  One time the SICI failed on me and I got a bad jstor ID, this way you do nothing 
More paranoid: Also double check url before assuming redirect is stable url

better jstor SICI verification

---

tests/phpunit/TemplateTest.php

ISBNs search Google to get GID.  GID is then used to search Google again.
Add GIDs to citations to skip a step.  
All we really care about is ISBN10 to ISBN13 in these tests

Remove unessesary Google Searches

---

Template.php

Some research shows that:
1.  the Google Books API has a "You must use an API key" license.  This is because the API is a very rich method for polling the Google Database.  Also, it has the ability to maintain personal libraries, interface with bookstores, etc..
2.  Books.Google.Com has a very liberal license.  
3.  We already use Books.Google.Com for {{citation|url=books.google.......+}}
4.  For ISBNs, we can get away with Books.Google.com
5.  Still need API for LCCN and OLCN
6.  I have applied for a bigger quota, but have not heard back

Prefer Books.Google.Com to GoogleAPIs.Com

---

Template.php
WikipediaBot.php
tests/phpunit/TemplateTest.php

{{citation}} templates that are not journals died because of this typo.
Also, no longer say "checking for ISBN" on citations that already have one.
Also find_isbn's arguments have changed, etc.

fix function name typos & add test for it

---

.travis.yml

Underscores vs dashes.
Once that was fixed, a bunch of the stuff did not work anyway, such as updating certificates

Parts of the build were not running

---

DOItools.php
Template.php
tests/phpunit/TemplateTest.php

We do not handle Latex math in titles (I do not know how we could).  Add test to make sure that do not make it worse than it already is.
Remove (sir) and (sir.) from authors and add test for it

Ignore honorifics in author names and add tests

---

Template.php
tests/phpunit/TemplateTest.php

Fixes oup accepted manuscript placeholder data from being used
Also includes a test -- at some point this will break, but it verifies path for now
Ready to merge I believe

Reject placeholder DOI data

---

Template.php

Fixes parameters moving around when not changed.
Uses two renames instead of forget and set

Avoid moving things around

---

Template.php
tests/phpunit/TemplateTest.php

Convert page ranges where the start and end match to a non range
Took forever because of multiple byte characters

Convert page range to pages if end=start

---

Template.php

CURL is printing standard out to log files 
This information is all present in the CURL data we parse, including errors etc.

Stop curl from printing output

---

Template.php
expandFns.php
tests/phpunit/TemplateTest.php
tests/phpunit/expandFnsTest.php

Also made punctuation arguments non-optional to encourage thinking about it
ucwords only uppercases words, does not lowercase the other letters I the word Which is what we need.

Journal Capitalization in tidy()

---

Template.php

No reason not to add jstor always.
JSTOR DOIs often do not resolve, but jstor stable always does

JSTOR is easy.  Always do it

---

Page.php
Template.php
tests/phpunit/PageTest.php

Keep track of template type before and after and add to arrays.
Check if set arrays are empty before using, instead of just checking for existence.
Remove empty elements from deletions array (they come from deleting empty element of double pipe)

Fix edit summary

---

Template.php

Do not check is DOI is set before calling get_doi_from_crossref().
This is checked inside.  
This basically makes the calls to get_doi_from_crossref() consistent about not checking.
We generally do not check, so this now follows our “standards”

standardize get_doi_from_crossref

---

Template.php
expandFns.php

We upper cases them.  Oops.
Also changed from [[...]] to [...] tonsuppprt both url and wiki links.

Ignore linked titles

---

Template.php

We check for CITATION_BOT_PLACEHOLDER before success, so use that for our placeholder

Better error checking

---

Template.php
tests/phpunit/TemplateTest.php

The other URL seems to not always be reliable.  Just plain "url" seems to involve some post-processing on their part (which is not always right):
https://api.oadoi.org/v2/10.1671/0272-4634(2002)022[0058:ADATDF]2.0.CO;2?email=not@telling.com
This also seems to be more likely to point to the description page instead of the final pdf, which is probably better since most people just want that.
Also, it gives a url more often.  See the test that is updated.

Prefer landing page url to url

---

Template.php
tests/phpunit/TemplateTest.php

We never set work, but people do.
Also do the template clean-up for more than just cite journal

Forget "work=" if same as other text

---

Template.php
tests/phpunit/TemplateTest.php

Do not URL encode DOIs.  They must have changed API. (This gives us PMID in test)
Also, after we find a PMID, we then look for a PMC.  (This then gives us PMC in test case)
Also added quotes around search terms.

Fix PubMed Searching

---

tests/phpunit/TemplateTest.php

Just a single line of debug output removed from tests

remove debug printout

---

Template.php
tests/phpunit/TemplateTest.php

Removes optional end text.
Changes http to https.
Normalizes to including the "www."
There is talk of adding the researchgate ID to the citation templates, so eventually this will probably just set that parameter instead.

Normalize researchgate URLS in tidy()

---

Template.php

1.  Do not echo when forgetting parameters that are set to nothing {{cite journal| forget_me=}}
2.  Do not echo when forgetting CITATION_BOT_PLACEHOLDER_year and such.
3.  Remove **empty** copies of parameters that are going to be overwritten.
{{cite journal | item1=|item2=X}}
rename('item2','item1') old code leads to:
{{cite journal | item1=|item1=X}}
but with new code leads to 
{{cite journal | item1=X}}

Better renaming and forgetting of parameters

---

Template.php
tests/phpunit/TemplateTest.php

The only thing we leave is if the entire name of a journal is a wikilink

Remove Wikilinks from journal & titles names

---

expandFns.php
tests/phpunit/expandFnsTest.php

"J Chem Phys e" is not the Spanish little word "e"

Uppercase lone letters at end of titles

---

Template.php
tests/phpunit/TemplateTest.php

Simpler Regex and case insensitive 
I even included a test

Shorten academia.edu urls & clean up researchgate

---

Template.php

citeseerx.ist.psu.edu, NOT citeseerx.ist.ps.edu
Also made code much simpler to read by assigning
$oa_url = $best_location->url_for_landing_page;
only one time

Fix citeseerx.ist.psu.edu

---

gadgetapi.php

The new php lint step actually does some verification these files now.   Cool.
I did verify this in a php environment.

Don't add[[WP:UCB|Assisted by Citation bot]] twice

---

.travis.yml

I finally ran across this:
https://stackoverflow.com/questions/27896816/how-to-check-if-master-branch-pushed-with-a-tag-under-travis
PHP 5.6 is specified explicitly since otherwise Travis assumes you want 5.5 which has to be downloaded and installed (and then never used by us)
I invite you to check out Travis CI output.

Fix deploy target

---

constants.php

They might someday do that.  Also, someone (or some bot) might change it to https and then we would not recognize it.  Future-proofing the code.

ready for https in bibcode URLS

---

Template.php

Avoid GIGO.  Pubmed needs to do a better job verifying their data.  Although technically 10.4244/ was a valid DOI, since the standard allows a zero length suffix.
Old code only needed 10.X, where X is at least single character.
New code requires 10.X/Y where X and Y are at least one character each.

Better DOI validation

---

Template.php
tests/phpunit/TemplateTest.php

Removes all [[ and ]] from titles: that is not new.
Full title wikilinks become title-link: that is not new.
What's new:
Single partial wikilinks get converted to title-link
https://en.wikipedia.org/wiki/User_talk:Citation_bot#Do_not_remove_partial_wikilinks_in_titles
In the case it is GIGO this makes it more likely for a human to fix, so it is still an improvement.

Better handling of wikilinks in titles

---

Template.php

I often look for FunctionName(  with no space.  This keeps it more consistent.

Make code more searchable

---

Template.php
apiFunctions.php

ID parameters should not contain non-breaking spaces, or they won't be `trim`med properly
Fixes #680 .

Remove nbsp from id

---

WikipediaBot.php

2 seconds to connect and 20 seconds to time-out on download
Honestly the 20 might be less than defaults but it is effectively infinite for us

Set curl time limits

---

WikipediaBot.php

Two minutes for the next step and 45 seconds to load a page
That’s php time only not wall clock
FIXES: we were setting time limits and not resetting them.

Set and reset time limits

---

DOItools.php
tests/phpunit/DOIToolsTest.php

Fixes websites the do sections using these instead of arrow:
Science » Chemistry » Physical Chemistry » Computational Chemistry » Super Heroes

Only remove double angle quotes if some of both

---

Template.php

Already did {{cite journal}}
Adding {{citation | journal=something}}

Do not add arXiv classes to journals

---

Template.php
apiFunctions.php
tests/phpunit/TemplateTest.php

mark_inactive_doi needs to be public not protected to call from API file
lots of url encoding for evil square bracket DOIs (and ending with -# is pure evil)
Add missing { } after if that lead to wrong code logic

Fix DOIs code especially for square brackets etc.

---

Comment.php
Page.php
tests/phpunit/TemplateTest.php

This bug report relates to parsing page Fouling

Remove <X>  </X> that can have unmatched {{ & }} inside

---

Template.php

https://stackoverflow.com/questions/1722453/need-to-prevent-php-regex-segfault
Please think about this, since this changes the RegEx, but I think that in our case the capture is exactly the same.
Please see https://github.com/ms609/citation-bot/pull/735 where this is tested.  Do not accept that pull for it includes the Vietnam War page that takes a minute to process with PHP 5.6.
Interestingly enough, in PHP 7 the page still gives up with FALSE, but with PHP 5.6 it actually parses.

Fix crashes on huge pages -- use atomic regex

---

Template.php
tests/phpunit/TemplateTest.php

Make code recognize all pages template elements when checking for existing dashes
Add special code to save pages that include "see " and "table"

Do not modify complex at= parameters

---

Template.php
apiFunctions.php

Avoid access violation

---

Template.php

This non-change pisses people off a shockingly amount.
Secondly it is GIGO often since bad information seems to put in the work parameter that should have been put somewhere else

Mess with work less

---

tests/phpunit/PageTest.php

When the first template is done alone it works on wikipedia.  When done with another template on Wikipedia (that has a bibcode) it goes nuts.  
I assume that if the code on wikipedia was updated this bug would not appear there.

Add test for Horrible bibcode bug

---

tests/phpunit/PageTest.php

The API finds the journal copy of the Noble Prize speech which changed the output, and it is no longer needed.

Remove uneeded test

---

Template.php
apiFunctions.php
tests/phpunit/TemplateTest.php
tests/phpunit/apiFunctionsTest.php

Need to learn to parse this data before we use it.
http://adsabs.harvard.edu/abs/2003hoe..book.....K
Add bogus journal data, etc.

Do not search book bibcodes

---

Template.php

Be more generous with URL expansion

---

Template.php
tests/phpunit/TemplateTest.php

Current code does [[]] and [[|]].  
Added up to this size:
[[File:Example.png|thumb|upright|alt=Example alt text|Example caption]]

[[file:img|12px|alt=words]] and such

---

Template.php

We assumed that our placeholders do not get lower-cased.  Which can happen.

do not assume case

---

Template.php
tests/phpunit/TemplateTest.php

- for conference papers, the `url` field is changed to `chapter-url`, because most open-access versions of conference papers point to the paper itself, and not to the whole proceedings

conference paper metadata uses "chapter-url"

---

Template.php
tests/phpunit/TemplateTest.php

n.d. is special.  Treat such dates special

---

Template.php
tests/phpunit/TemplateTest.php

publication-place: If any one of publication-place, place, or location is defined, the location will show after the title; if publication-place and place or location are defined, then place or location is shown before the title prefixed with "written at" and publication-place is shown after the title.
publication-date: Date of publication when different from the date the work was written. Displays only if year or date are defined and only if different, else publication-date is used and displayed as date.
orig-year: Original publication year; displays after the date or year. For clarity, please supply specifics. For example: |orig-year=First published 1859 or |orig-year=Composed 1904. Alias: origyear

Fix parameter choices in tidy

---

Parameter.php
Template.php
tests/phpunit/TemplateTest.php

have to include in set() since it is main point of changing
also have to include in add_if_new() since it has side effects
also have to include in add() since it echos its changing to the user
And other places too. 👎

comment exclusion

---

Template.php
constants/capitalization.php
expandFns.php

Fix BMC problem-We were not dealing with 1st word

---

Template.php

vastly more paranoia about both title and script title
Require that new title be basically English characters and that script-title not be English characters.   Turns out that odd things can happen with languages that have multiple character set choices

Script title

---

Template.php

The code has changed over time and this is not called from outside

Not called form page() anymore

---

Template.php

process() is no longer main driver for doing template expansion 
This code is very misleading.   It is not the main zoreto call

Already done in API call.  Do not zoreto twice

---

constants/bad_data.php

the {{ and }} might catch some real things, better safe than sorry

Add more bad titles

---

apiFunctions.php
tests/phpunit/TemplateTest.php

JSTOR has books.  The jstor= template parameter does not support them so they are urls.  We can expand them

Add jstor book support

---

apiFunctions.php

Old code assumed $template was defined (it was not)
Old code assumed that $ids and $templates were in same order with no duplicates.
Also, fixed case where all $ids had book or & symbol and there were no ids left

Expand bibcodes with & symbol correctly

---

api_handlers/zotero.php
tests/phpunit/zoteroTest.php

Do after doi and isbn since they are probably not changing.  Also allows us to often drop the url once we get a DOI.  
Test added too (without being nagged)

Respect access-dates

---

Template.php
apiFunctions.php
tests/phpunit/TemplateTest.php

Current code "counted" empty authors.  Why pubmed gives us those, I do not know.
Tests added too (without being asked)

Do not add Author2 without author1

---

expandFns.php
tests/phpunit/expandFnsTest.php

By “support” mean fire napalm at
This is a heavy hammer  for the non-English Whack a mole.
Tests added too (without being asked)
Use "-", not "/", since strtodate assumes Non-american for "-" and american for "/"
Also a few more random things

Better support for non-english dates

---

Template.php

Open access database calls this an archive, but it is where the doi points to

Reject bioone.org/doi

---

Template.php
constants/regular_expressions.php

Saw bot change authorn= to author2= that’s pretty random since empty
No point changing junk to something that might not make sense in the template context

Just forget empty unrecognized parameters

---

Template.php
tests/phpunit/TemplateTest.php

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2491514/pdf/annrcse01476-0076.pdf
vs
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2491514/
The trailing slash is needed in the test, otherwise it re-directs to the slash and you do not get 404

Some PMCs do NOT resolve.  So leave URL

---

api_handlers/zotero.php
constants/bad_data.php

If the bot includes stuff such as `- health.gov` in the title, it is a bad title, since is a lot of junk which should not be in the title.

Disallow top-level domain names in titles

---

Template.php
constants/bad_data.php

Bot should change
https://zenodo.org/record/895627/files/article.pdf to
https://zenodo.org/record/895627
https://zenodo.org/record/1117219#.Wobg1K6nHX4 to
https://zenodo.org/record/1117219

Normalize zenodo urls

---

Template.php

fix open-access url when oadoi returns no url_for_landing_page
- check for null value in JSON field url_for_landing_page
- prefer PDF url is one exists

fix: fix open-access url when oadoi returns no url_for_landing_page

---

Template.php

Even if they did work then they would just point to publisher anyway
Such as    http://gateway.isiknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcAuth=HighwireFree&SrcApp=PRODUCT_NAME&KeyAID=http://jeb.biologists.org_209_15_2829&DestApp=HighwireFree&SrcAppSID=APP_SID&SrcJTitle=WURS_TITLE

gateway.isiknowledge.com urls are worthless

---

constants/bad_data.php

`<ref>https://web.archive.org/web/20051231112918/http://www.linguasphere.org/auswanderungs_deutsch.pdf</ref>`
`<ref>{{cite web | url=https://web.archive.org/web/20051231112918/http://www.linguasphere.org/auswanderungs_deutsch.pdf | title=Wayback Machine}}</ref>`

Wayback Machine

---

Template.php
tests/phpunit/TemplateTest.php

If the DOI is rubbish, then the URL is rubbish too

Even if the DOI is broken, drop doi.org URL

---

Template.php

"Some identifiers always link to free full texts. In this case, the access level is automatically indicated by the template. This is the case for |arxiv=, |biorxiv=, |citeseerx=, |pmc=, |rfc= and |ssrn=."

 Do not add OA url if free ID exists

---

DOItools.php
tests/phpunit/TemplateTest.php

Only care about loss of url and only having one jstor= block.
Thus, merge into a different test.

Simplify Jstor tests

---

DOItools.php
Template.php
constants/bad_data.php

Normally not a big deal, but people put this in the Open-Access data-base as the URL (Because that is soooooo different from dx.doi.org resolving to the exact same final URL.

doi.library.ubc.ca is a DOI resolver too

---

Template.php

Different data sources have different names for same data
Probably should change to str_equivalent() after/before other pull -- depending who goes first

Do not add series that matches title

---

Page.php
Template.php
generate_template.php
tests/phpunit/PageTest.php
tests/phpunit/TemplateTest.php

Fixed:
Existing code output depended upon capitalization of code calling change_name_to()
Existing code checked for 'cite book' with case specificity, which is a bug
Feature added:
If the cit in {{citation or {{cite... is lower case, then keep it that way.
Note that in some cases before, the type of citation could get changed from {{cite book| to {{Cite journal| and then to {{Cite book|, so the capitalization only got changed.
Code cleaning:
Standardized on calling change_name_to() with all lower case instead of mixture
Standardized on capital letters whenever we create the template out of nothing
Warning:
This makes some of the tests have a different case than before.

Preserve existing capitalization of cite

---

README.md
Template.php
user_messages.php

If that little call to process() is still needed, then we need to think about why we do not do it every time we change to cite book.  
Secondly, if for some reason this call is needed, then probably best to just inline the parts that matter instead of calling process(), which calls prepare() and bunch of other stuff.
This is just part of the "process() - big pull" pull, in case you want something smaller

process() - little pull

---

api_handlers/zotero.php

Otherwise it gives a "Could not parse JSON for URL" error followed by <html.....

Human readable error message instead of HTML text

---

Template.php
tests/phpunit/TemplateTest.php

These dois never resolve
http://opil.ouplaw.com/view/10.1093/law:epil/9780199231690/law-9780199231690-e1301 and such
http://oxfordindex.oup.com/view/10.1093/oi/authority.20110803095840253?rskey=mH20Zr&result=0&q=gagan
also lead to DOIs the never work
I think I just manually removed all these from wikipedia
These are also 10.1093 DOIs like the other pull, but these do not truncate to anything that resolves.

10.1093 URLs that look like DOIs, but never work as DOIs

---

Template.php
tests/phpunit/apiFunctionsTest.php

For some reason, jstor urls are very prone to having a proxy in them

add support for proxy jstor urls

---

Template.php
constants/bad_data.php

We hit websites like CNN.com over and over again even when we do not have to and will gain nothing.

Better support for non-journal websites

---

Template.php

Do not change to cite arXiv if it contains parameters that cite arXiv does not support

cite arXiv does not support some parameters

---

api_handlers/zotero.php
tests/phpunit/PageTest.php

Some translators just dump stuff in "extra". 
Error checking and data verification done.
@ms609 changes made to guarantee only do this if one DOI.

Doi hidden in “extra”

---

Template.php
tests/phpunit/TemplateTest.php

Current code always uses last value seen as valid value -- so viewed citation is unchanged.

Prefer values over empty strings

---

Template.php
apiFunctions.php

Exising calls to dx.doi.org can result in a URL, that exactly matches the one that the doi directs to of course.

do not add urls from dx.doi.org or JSTOR

---

Template.php

Just a code path that we did not take into account before.  I think usually the citation is mostly already expanded when we add this bibcode and so we rarely add things wrong.

Use book BibCode code when adding book BibCodes

---

Template.php
tests/phpunit/TemplateTest.php

CS1 and CS2 templates detect .PDF and .pdf and automatically set the format.
The linking to PDF wikipage is silly too
Also, the format= item only applies to URLs, not chapter-urls, etc.
And yes there was a discussion about this on wikipedia
Had to change  |format=PDF to  |format=DUDE in a test to keep it from being deleted!

Remove outdated template clutter

---

Page.php
Template.php

By using a couple Regex to sneak up on the real one, we are able to avoid out of memory errors.  We first look for templates with no set braces or pipes, then ones with no set braces, and finally the full Regex.   The fewer templates to find and the fewer extraneous {  and } floating around the less memory the final Regex needs.
Fixes Deim_Zubeir

Fix regex out of memory errors

---

Template.php
tests/phpunit/TemplateTest.php

We were changing dashes in hidden urls
{{cite book|pages=[//books.google.com/books?id=-_rxBwAAQBAJ&pg=PA107 107]}}
See tests added.

Do not change this hidden URL

---

Template.php

Add a bunch more types of URLs to look at.
More importantly, if there is both a url and a chapter-url, then we prefer the chapter one, and we do not delete either one of them when we are done.

Better URL handling

---

constants/bad_data.php

Removed redundant math.ph (since we include just plain math).

add 'cond.mat', 'cs.' and 'astro.ph'

---

Template.php
tests/phpunit/TemplateTest.php

Example:
https://en.wikipedia.org/?diff=878079480
Coming from `"page":"0-0"` in:
https://api.crossref.org/works/10.1111/j.1755-3768.2010.4142.x

Avoid returning "0" as page number/range

---

Template.php

sometimes this returns something and it is wrong
DOI:10.1126/science. returns https://eprints.utas.edu.au/2614/1/Science2007.pdf  👎 
Also it is a waste of time, since there is probably nothing to find

This search will not help

---

api_handlers/zotero.php

With a hundred references and one minute per Zotero request, the job
can easily take hours. Just skip when the Zotero server is too slow.
* 1 second should be plenty to connect to a local server.
* 5 seconds is enough when the server is actually working.
https://curl.haxx.se/libcurl/c/CURLOPT_TIMEOUT.html

Switch Zotero to HTTPS and reduce timeout

---

apiFunctions.php

<crossref_result xmlns="http://www.crossref.org/qrschema/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0" xsi:schemaLocation="http://www.crossref.org/qrschema/2.0 https://www.crossref.org/schema/crossref_query_output2.0.xsd">
<query_result>
<head>
<doi_batch_id>none</doi_batch_id>
</head>
<body>
<query status="resolved" fl_count="0">
<doi type="journal_article">10.2165/00126839-200203020-00006</doi>
<issn type="print">1174-5886</issn>
<journal_title>Drugs in R & D</journal_title>
<contributors>
<contributor sequence="first" contributor_role="author">
<surname>&NA;</surname>
</contributor>
</contributors>
<volume>3</volume>
<issue>2</issue>
<first_page>106</first_page>
<last_page>108</last_page>
<year media_type="print">2002</year> …

catch bad crossref data

---

tests/phpunit/PageTest.php
tests/phpunit/TemplateTest.php

This way when you have tests that fail, you easily remember that ‘stupid zotero’ instead of ‘what did I do to the dates code??’   I am getting too old to remember these things.

Add zotero to test name

---

Page.php

Just seem the crappiest data should be used last.
Secondly, a whole lot of the calls to zotero will be avoided with the "profoundly_incomplete()".  That might save us from most of our hangs.
Not random, this is yet another change noticed during the ISSN only DOI problems fixing

zotero should be done last, not before PMID etc.

---

Template.php
tests/phpunit/TemplateTest.php

Current code drop location/publisher very early in the expansion process from Journals.
This code moves that to the very end (in final_tidy). 
The reason being that during the expansion, we sometimes detect that it is really a book/etc.  This way we do not drop publisher/location and then regret it when we figure out that we had a book.

Don’t Remove publisher/location too early 

---

Template.php
tests/phpunit/TemplateTest.php

Page range code was wrong, so even after the other fix, we were still not always finding them.
Also, we confused Object with Array, so even if we found stuff, we still did not add it.
@ms609 added a test too, since we kinda sucked on this.

Actually search Crossref for DOIs

---

api_handlers/zotero.php
tests/phpunit/zoteroTest.php

* Do not require URL to match some narrow regexes before resolving redirects.
* Fix regex typo introduced in 36c462860a6b003fd424bc3b6a7b98b1c962f740.

improve URL=DOI code

---

WikipediaBot.php

Unlike some other unused code.  I cannot imagine this ever being useful.
Especially since Wikipedia now has a purge url for this 
It is a code path to writing a page, so eliminating it is a good step towards using oauth with users.

remove unused {{cite doi}} code

---

category.php
process_page.php

Need to do this before everything else, if we are going to start authenticating users
@session_start() with @ symbol, so all errors are ignored, such as command-line not web, etc.
Any page we are going to call write() from

Call @session_start() for all PHP pages that write()

---

Page.php
tests/phpunit/PageTest.php

Done: Report url dropping

---

Page.php

Should be faster without creating extra $api class objects all over the place.
Also remove false oauth references from code that make adding User oauth impossible

Done: API is not page specific - remove unused code

---

Template.php

GIGO protection.  This might seem silly, since pages=33-33 gets fixed later, but this means the existing page=33 gets changed to pages=33-33 and then to pages=33, which is a cosmetic change.

JSTOR sometimes sends first page as end page too

---

Template.php

If the replace array is too short, then you get blanks.  Actually works in most cases, but not all of these cases.

str_replace() usage mistake

---

Page.php
Template.php
WikipediaBot.php
apiFunctions.php
user_messages.php

Report an error message for semi-recoverable conditions, instead of dieing in trigger_error().  
Instead of calling  trigger_error() for fatal problems call new report_error() which prints the error if not TRAVIS and then that calls trigger_error() to die -- and give error in TRAVIS.
This pull came about because blocked bot gives no error messages when trigger_error() is called.

Better error handling

---

gadgetapi.php

If we hit nobots or other problems, then the gadget api passes crap back

Deal with errors in gadget API

---

gadgetapi.php
tests/phpunit/TemplateTest.php

But leave check for empty data just in case
For so reason, the "new" code was not working perfectly either when no changes were made.  Odd

VERY HIGH PRIORITY:  Fixes to page() make this check not needed anymore

---

.travis.yml
Template.php
docs/CONTRIBUTING.md
tests/phpunit/TemplateTest.php
tests/phpunit/constantsTest.php

FILTER_FLAG_HOST_REQUIRED actually is meaningless in PHP 5.6 and 7.*
String functions are getting more picky about passing them strings instead of numbers.
7.3 capitalization is better with &

COOL: Travis supports PHP 7.3 now

---

expandFns.php

$crossRefOnly is not used anymore
pmid=##### and doi=10.####/##### code is gone

LOW PRIORITY BUT EASY: Remove old {{Cite pmid}} and {{cite doi}} code

---

expandFns.php
tests/phpunit/TemplateTest.php

GIGO protection.  Note that < is not allowed in the central area, prevents us from add GIGO to GIGO

LOW PRIORITY: <Emphasis Type="Italic"> and such

---

constants.php
generate_template.php
tests/phpunit/TemplateTest.php

Never use require() or include().  Always use the _once versions.

LOW PRIORITY, BUT EASY:  Prefer require_once()

---

.travis.yml
Template.php
apiFunctions.php
tests/phpunit/TemplateTest.php

By moving to newer 5.6 we get a better php, that is not travis provided and thus not deficient.
The last lines of PHP_VERSION_ID code we have
This brings code on Travis in-line with Wikipedia php code

SUPER COOL:  Remove TRAVIS PHP 5.6 specific code

---

Template.php

Existing code does not drop urls if the bibcode parameter is set already.  
New code drops url (only after making sure the new and old bibcode match of course).

remove redundant bibcode URLs

---

Template.php

The meta data in 'jounral' is most likely identical to something else (and often not exactly the same: j.chem.phys. vs. J Chem Phys, etc).  Basically most likely add duplicate data.

Do not add journal if book has everything else

---

Template.php
tests/phpunit/TemplateTest.php

Some one thinks that adding CiteSeerX links is a copyright violation.
It is NOT WP:ELNEVER, despite the original discussion.
It is covered under the looser standard of WP:COPYLINK.  I tried to get a debate going, but it was like trying to get people to discuss potaoes going rotten.  Given the lack of debate the default is not add links.

UN-BLOCK the BOT :-(

---

Template.php

It comes from trim().  Cannot be an integer

$value is by definition a string

---

Template.php

This often happens when a template is unclosed and all the parsing goes insanely wrong
https://en.wikipedia.org/w/index.php?title=Calcium_carbonate&type=revision&diff=887674726&oldid=885707535

Error on reference within citation template

---

category.php
expandFns.php
gadgetapi.php
process_page.php
tests/testBaseClass.php

Why not?  Because PHP says so.  Because they are automatically global in scope.
Foolishly added by me, since I could not see why gadget api did not expand bibcodes.  I figured that out and it is in another pull #1547

Not supposed to use global outside of functions

---

expandFns.php
process_page.php

It only works now because it is a global

Move $ON to where used

---

category.php
expandFns.php
gadgetapi.php

Move buffer starting higher up on code to catch "Reading tokens...." text in buffer too.
This means that we no longer need to start buffering in gadget page.
Lastly this means we only have to free one buffer in gadget.
Lastly — I really mean it this time — exit() Call’s flush too, so no need to call right before exit() calls.

Fix output buffering code

---

.gitignore
gitpull.php

It _appears_ that the GIT problems must be caused by files that we are creating that need to be added to git ignore.  Time to list them in debug output.
Also make the HTML text an "echo" instead of outside of PHP.
And add all the extra HTML tags too, just because.

Better GIT debug

---

Template.php

Temporary blacklist reverted in https://en.wikipedia.org/?diff=891633158
per discussion at https://en.wikipedia.org/?oldid=891630577#zenodo.org .
Reverts d9753a5a, bd7557e7.

Revert Zenodo temporary skip

---

gadgetapi.php
tests/phpunit/gadgetTest.php

Reset everything that Gadget does differently from other tests.
Fix "risky" test by allowing PHP Unit to keeps its output buffer

Improve gadgetTest.php

---

Template.php

Since this blacklist was added, Unpaywall/OAdoi has improved accuracy.
OAI-PMH author and title match also gets higher priority compared to other
methods like trusting whatever the metadata claims about DOI relationships.

Do not throw away Unpaywall OAI-PMH matches

---

Template.php
apiFunctions.php

Use qa.adsabs for testing, to avoid depleting api.adsabs queries.

Initial test against QA.adsabs

---

tests/phpunit/DOIToolsTest.php
tests/phpunit/PageTest.php
tests/phpunit/ParameterTest.php
tests/phpunit/TemplateTest.php
tests/phpunit/WikipediaBotTest.php
tests/phpunit/apiFunctionsTest.php
tests/phpunit/constantsTest.php
tests/phpunit/expandFnsTest.php
tests/phpunit/gadgetTest.php
tests/phpunit/zoteroTest.php
tests/testBaseClass.php

assertSame does ===
assertEquals does ==
This change makes tests slightly more strict and probably a nano-second faster.
This forces us to be more carefull about NULL vs. FALSE vs. '', and such things

assertSame

---

authenticate.php

The protocol header is set differently on toolforge than it is locally. Allowing for both fixes the problem on toolforge.

Allow the proto to be set by a header

---

zotero.php

If a request takes more than 5 seconds it may never succeed.
A page can have hundreds of links and spend hours on it with
a 10 seconds timeout.
https://en.wikipedia.org/wiki/User_talk:Citation_bot/Archive_17#Fails_on_Soil
https://en.wikipedia.org/?oldid=909325894#Better_batch/queuing_handling

Reduce timeout in Zotero requests

---

.lighttpd.conf

The bot is currently impossibly slow to use for single pages while it is
successfully managing two large categories at once.
https://en.wikipedia.org/w/index.php?title=Special:Contributions&dir=prev&offset=20190828081954&limit=500&target=Citation+bot

Try to increase concurrency by half

---

index.php
tests/phpunit/PageTest.php

This prevents an undefined variable error being thrown every time someone loads the index page.

Prevent undefined variable errors from $the_example_user

---

.github/workflows/php-static2.yml
Template.php
Zotero.php
apiFunctions.php
env.php.example
phpstan.neon
setup.php

This pull request adds ability to specify PubMed API Key and email via enrvironment variable.
See `env.php.example`:
```
@putenv('NLM_APIKEY=xxxxx');       // API key for *nlm.nih.gov, can be obtained at https://account.ncbi.nlm.nih.gov/settings/
@putenv('NLM_EMAIL=xxxxx');        // Email address for *nlm.nih.gov
```
If no PubMed email is specified in the environment variable (or `xxxxx` is specified), the default value from constants.php will be used. If no API Key is specified (or `xxxxx` is specified, or a value shorter than 8 characters is specified, then this parameter will not be passed to PubMed as was before. The API key allows higher request rate. You can get one from https://account.ncbi.nlm.nih.gov/settings/
Also, if you specify the PubMed API key, then it will not try one …

Ability to specify PubMed API Key and email via enrvironment variable

---

expandFns.php
progpilot.json

When a DOI check or a HDL check returned with a timeout, do not try gain multiple time this DOI.
A DOI check can return one of the following results:
* TRUE: DOI OK
* FALSE: DOI Fail
* NULL: check again later
In the past, DOIs such as 10.3746/pnf.2017.22.2.67 took about a minute to check to pass all the timeouts, still that URL returned NULL and was rechecked over and over again. Now, with this pull request, a time is measured low long did it take to check a DOI. If it took more than a timeout (BOT_CONNECTION_TIMEOUT or BOT_HTTP_TIMEOUT, whichever larger), than we consider that this check returned FALSE (Fail) rather than NULL, so we would not recheck such slow DOIs. Only DOIs which returned quickly will be rechecked.
With this pull request, the bot no longer spends hours on DOIs such as …

When a DOI check or a HDL check returned with a timeout, do not try gain multiple time this DOI

---

Template.php
WikipediaBot.php
Zotero.php
apiFunctions.php
expandFns.php

There were a few places where CURLOPT_FOLLOWLOCATION parameter was omitted (missing), which might have resulted errors such as '!CrossRef server error loading headers for DOI 10.1128/MCB.00807-06 : HTTP/1.1 302 Found' when working via a proxy. With this option, Curl handles all the redirects, including 302 Found and continues, returning proper content.

There were a few places where CURLOPT_FOLLOWLOCATION parameter was omitted (missing)

---

Page.php
tests/phpunit/PageTest.php
tests/phpunit/TemplateTest.php
tests/phpunit/gadgetTest.php

Better edit summary for singulars, i.e, when only 1 (one) change or alteration was done, the semicolon is not used, and a different, friendlier form of the verb is used.
For example, instead of former use of "Add: s2cid." it will be "Added s2cid."
But when the number in the list is higher than one, the old algorithm is used, i.e., "Add: pages, issue, volume."

Better edit summary for singulars in "Add" and "Alter"

---

apiFunctions.php

Errors that were not related to rate limit reached were erroneously understood as rate limit reached for AdsAbs. For example on some data parsing errors the bot did react as the limit reached for accessing AdsAbs database. This was because the exact values of limits for AdsAbs were not checked. 
The error could be reproduced on the page "Stomach cancer":
```
php process_page.php "Stomach cancer" --slow
```
This pull request institutes the proper checking of the limits.

Errors that were not related to rate limit reached were erroneously understood as rate limit reached for AdsAbs

---

Template.php

When there were CrossRef disagree on volume and issue, there was a message, but it was impossible to determine to which of the citations it was applied. Now the doi details are echoed, so it is now possible to understand to each template it applies. Also, it also prints the values of volume and issue listed in Crossref.
Example of the message as it was displayed in the past:
```
.Citation has volume and issue set to 3 which disagrees with CrossRef
```
Example of the message in this pull request:
```
.Citation for doi:10.1002/14651858.CD005612.pub5 has volume and issue set to 3 which disagrees with CrossRef (volume 2022, issue 4)
```
To reproduce the issue, run:
```
php process_page.php "Pregabalin" --savetofiles 
```
The proposed code change only affects the echo output when run from the …

Crossref disagree details are echoed (it was impossible to determine to which citation this message applied)

---

Template.php

- removed duplicate `and` from the `SHORT_STRING` constant;
- `DEPARMENTS` renamed to `DEPARTMENTS` to fix typo in the constant name; removed duplicate `world` and `arts` entries from this list.

Typos and repetitions in constants

---

constants/translations.php

- Adding Vietnamese translations per [discussion](https://en.wikipedia.org/w/index.php?title=User_talk:Citation_bot&oldid=1301912040#Internationalization_-_VI).

Adding Vietnamese translations
